package cn.med.dao;



import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import cn.med.entity.CwCheckWork;

public interface CwCheckWorkDao {


    
    
    /**
     * 查询单个
     * @param mId
     * @return
     */
    @Select({
    	 "select",
         "id, cw_userid, ambegin_time, ambegin_state,amend_time,amend_state,pmbegin_time,pmbegin_state,pmend_time,pmend_state,coordinate,creat_time,remark ",
         "from cw_checkwork",
         "where   to_days(creat_time) = to_days(now()) and cw_userid = #{userId,jdbcType=INTEGER}"
    })
    @Results({
    	 @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
         @Result(column="cw_userid", property="userid", jdbcType=JdbcType.INTEGER),
         @Result(column="ambegin_time", property="ambegin_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="ambegin_state", property="ambegin_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="amend_time", property="amend_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="amend_state", property="amend_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmbegin_time", property="pmbegin_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmbegin_state", property="pmbegin_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmend_time", property="pmend_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmend_state", property="pmend_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="coordinate", property="coordinate", jdbcType=JdbcType.VARCHAR),
         @Result(column="creat_time", property="creat_time", jdbcType=JdbcType.TIMESTAMP),
         @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    CwCheckWork selectCkByUserId(int userId);

    /**
     * 查询单个
     * @param mId
     * @return
     */
    @Select({
    	 "select",
         "id, cw_userid, ambegin_time, ambegin_state,amend_time,amend_state,pmbegin_time,pmbegin_state,pmend_time,pmend_state,coordinate,creat_time,remark ",
         "from cw_checkwork",
         "where   to_days(creat_time) = to_days(#{0}) and cw_userid = #{1}"
    })
    @Results({
    	 @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
         @Result(column="cw_userid", property="userid", jdbcType=JdbcType.INTEGER),
         @Result(column="ambegin_time", property="ambegin_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="ambegin_state", property="ambegin_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="amend_time", property="amend_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="amend_state", property="amend_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmbegin_time", property="pmbegin_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmbegin_state", property="pmbegin_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmend_time", property="pmend_time", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmend_state", property="pmend_state", jdbcType=JdbcType.VARCHAR),
         @Result(column="coordinate", property="coordinate", jdbcType=JdbcType.VARCHAR),
         @Result(column="creat_time", property="creat_time", jdbcType=JdbcType.TIMESTAMP),
         @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    CwCheckWork selectCkByUserAndDate(String date,int userId);
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Insert({
        "insert into cw_checkwork (id, cw_userid, ",
        "ambegin_time, ambegin_state,amend_time,amend_state,pmbegin_time,pmbegin_state,pmend_time,pmend_state,coordinate,creat_time,remark)  ",
        "values (#{id,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{ambegin_time,jdbcType=VARCHAR}, #{ambegin_state,jdbcType=VARCHAR},#{amend_time,jdbcType=VARCHAR},#{amend_state,jdbcType=VARCHAR},",
        "#{pmbegin_time,jdbcType=VARCHAR},#{pmbegin_state,jdbcType=VARCHAR},#{pmend_time,jdbcType=VARCHAR},#{pmend_state,jdbcType=VARCHAR},",
        "#{coordinate,jdbcType=VARCHAR},#{creat_time,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(CwCheckWork checkWork);
    
    
    
    
    @Update({
        "update cw_checkwork",
        "set ambegin_time = #{ambegin_time,jdbcType=VARCHAR}, ambegin_state = #{ambegin_state,jdbcType=VARCHAR},",
        " amend_time = #{amend_time,jdbcType=VARCHAR}, amend_state = #{amend_state,jdbcType=VARCHAR},",
        " pmbegin_time = #{pmbegin_time,jdbcType=VARCHAR}, pmbegin_state = #{pmbegin_state,jdbcType=VARCHAR},",
        " pmend_time = #{pmend_time,jdbcType=VARCHAR}, pmend_state = #{pmend_state,jdbcType=VARCHAR},",
        " coordinate = #{coordinate,jdbcType=VARCHAR}, creat_time = #{creat_time,jdbcType=VARCHAR},remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateCheckWork(CwCheckWork checkWork);
    
 
}