package cn.med.dao;


import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import cn.med.entity.CwDepartment;
import cn.med.entity.CwEnclosure;
import cn.med.entity.CwWorkTime;
import cn.med.entity.Medicine;

public interface CwEnclosureDao {


    
    
    /**
     * 查询单个
     * @param mId
     * @return
     */
    @Select({
    	 "select",
         "id, depart_id, enclosure, remark ",
         "from cw_enclosure",
         "where  depart_id = #{departId,jdbcType=INTEGER}"
    })
    @Results({
    	 @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
         @Result(column="depart_id", property="departid", jdbcType=JdbcType.INTEGER),
         @Result(column="enclosure", property="enclosure", jdbcType=JdbcType.VARCHAR),
         @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    CwEnclosure selectDepartById(String departId);
    

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Insert({
        "insert into cw_enclosure (id, depart_id, ",
        "enclosure,remark)  ",
        "values (#{id,jdbcType=INTEGER}, #{departid,jdbcType=INTEGER}, ",
        " #{enclosure,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}) "
    })
    int insert(CwEnclosure enclosure);
    
    
    
    
    @Update({
        "update cw_enclosure",
        "set enclosure = #{enclosure,jdbcType=VARCHAR} ",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateEnclosure(CwEnclosure enclosure);
    
    
    /**
     * 删除指定围栏
     * @param datas
     * @return
     */
    @Delete({
        "delete from cw_enclosure",
        "where id = #{eid,jdbcType=INTEGER}"
    })
    int deleteEnclosure(Integer eid);
}