package cn.med.dao;


import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import cn.med.entity.CwDepartment;
import cn.med.entity.CwWorkTime;
import cn.med.entity.Medicine;

public interface CwWorkTimeDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */

    
    
    /**
     * 查询单个
     * @param mId
     * @return
     */
    @Select({
    	 "select",
         "id, work_code, amstart_time, amend_time,pmstart_time,pmend_time, remark,work_type ",
         "from cw_worktime",
         "where  work_code = #{workcode,jdbcType=INTEGER}"
    })
    @Results({
    	 @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
         @Result(column="work_code", property="work_code", jdbcType=JdbcType.VARCHAR),
         @Result(column="amstart_time", property="amstarttime", jdbcType=JdbcType.VARCHAR),
         @Result(column="amend_time", property="amendtime", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmstart_time", property="pmstarttime", jdbcType=JdbcType.VARCHAR),
         @Result(column="pmend_time", property="pmendtime", jdbcType=JdbcType.VARCHAR),
         @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
    	 @Result(column="work_type", property="work_type", jdbcType=JdbcType.INTEGER)
    })
    CwWorkTime selectWtByCode(String workcode);
    


    
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Nov 15 22:11:44 CST 2018
     */
    @Insert({
        "insert into cw_worktime (id, work_code, ",
        "amstart_time, amend_time,pmstart_time,pmend_time,remark,work_type)  ",
        "values (#{id,jdbcType=INTEGER}, #{work_code,jdbcType=VARCHAR}, ",
        "#{amstarttime,jdbcType=VARCHAR}, #{amendtime,jdbcType=VARCHAR}, ",
        "#{pmstarttime,jdbcType=VARCHAR}, #{pmendtime,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR},#{work_type,jdbcType=INTEGER})"
    })
    int insert(CwWorkTime workTime);
    
    
    
    
    @Update({
        "update cw_worktime",
        "set amstart_time = #{amstarttime,jdbcType=VARCHAR}, amend_time = #{amendtime,jdbcType=VARCHAR},",
        " pmstart_time = #{pmstarttime,jdbcType=VARCHAR}, pmend_time = #{pmendtime,jdbcType=VARCHAR} , work_type = #{work_type,jdbcType=INTEGER} ",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateDepart(CwWorkTime workTime);
    
    
    /**
     * 删除指定部门
     * @param datas
     * @return
     */
    @Delete({
        "delete from cw_worktime",
        "where work_code = #{code,jdbcType=VARCHAR}"
    })
    int delWorkTime(String work_code);
    

  
}